### ISSUE TITLE
Support Thunderbird 60

### ISSUE THREAD

**Issue by crayxt** [fabrixxm/Year-View#21]
Hi,
It looks like this awesome extension does not support latest versions of Thunderbird.
Could you please update it?
Thanks,

**Comment by fabrixxm** [comment]
As soon it's released and I get the update, I'll check the extension and I'll update it.. 👍 
I'm sorry, but I don't have too much time for this, and to test beta releases of tb..

**Comment by gdsotirov** [comment]
@fabrixxm Thunderbird 60 is offered as stable since August 6-th. If you need any help updating the extension, please write me, because I'm really used to this "awesome extension" as @crayxt wrote.

**Comment by fabrixxm** [comment]
Looks like update it to Thunderbird 60 / Lightning 6.2 won't be easy. I'm on it, but don't hold your breath :-)

**Comment by fabrixxm** [comment]
Work in progress in branch tb-60

**Comment by fabrixxm** [comment]
Should be resolved in v0.6.0

**Comment by gdsotirov** [comment]
Hmm... just installed it from file (as still not available from addons.mozilla.org), but the "Year" tag in calendar grid doesn't appear...

**Comment by fabrixxm** [comment]
My bad, I *only* forgot to add the chrome folder in the zip :man_facepalming: 

I've updated the xpi
I've also delayed the release on amo, because I have some more small things to fix before.

**Comment by gdsotirov** [comment]
Just installed the new xpi, but "Year" tab is still not visible...

**Comment by fabrixxm** [comment]
@gdsotirov the file "Year-View-v0.6.0-1.xpi" ?
I've tested it on a brand new installation of TB 60.0 with Lightning 6.2 and it worked.
Have you restarted thunderbird?
Can you send me the errors log ( menu -> Tools -> Developer Tools -> Error Console) ?

**Comment by gdsotirov** [comment]
@fabrixxm Yes, I used Year-View-v0.6.0-1.xpi file and yes, I have restarted.
I now tried installing the extension in debug mode and I received the following error:

```
Error: Only restartless (bootstrap) add-ons can be installed from sources:
Stack trace:
installAddonFromLocation@resource://gre/modules/addons/XPIProvider.jsm:3585:13
 1 Controls.js:85:9
	installAddon/< resource://devtools/client/aboutdebugging/components/addons/Controls.js:85:9
```

Does this help?

**Comment by gdsotirov** [comment]
Otherwise, the extension installs and then in the console I have:

```
13:38:19.821 XML parsing error: undefined entity
Place: chrome://calendaryearview/content/calendaryearview-overlay-sidebar.xul
Row 16, column 9: 1 calendaryearview-overlay-sidebar.xul:16:9
13:38:19.822 XML parsing error: undefined entity
Place: chrome://calendaryearview/content/calendaryearview-common-sets.xul
Row 17, column 5: 1 calendaryearview-common-sets.xul:17:5
13:38:19.822 XML parsing error: undefined entity
Place: chrome://calendaryearview/content/calendaryearview-overlay.xul
Row 15, column 3: 1 calendaryearview-overlay.xul:15:3
```

I'm not sure if these are the reason, but "Year" tab still doesn't appear for me.

**Comment by fabrixxm** [comment]
hm no.
It says that you can't install year-view in debug mode because is not a "restartless" extension.
In fact year-view it's a old-style extension which needs a reload.

But if you just install it normally, and it does some error, you should see it in error console. 
Anything related with year-view in log should mention "calendaryearview".

**Comment by fabrixxm** [comment]
> Otherwise, the extension installs and then in the console I have: [...]

Ok, that's help. :-)

**Comment by fabrixxm** [comment]
looks like it doesn't load the locale dtd file.
I'm supposing you're using the "br" locale on your computer, so it should try to load you "br" translation files. They looks fine as dtd file, the only thing I find is they are utf16-encoded. If that's the problem, can you try this new version with the two files converted to utf8 and see if it works?

[Year-View-v0.6.0-2.zip](https://github.com/fabrixxm/Year-View/files/2416114/Year-View-v0.6.0-2.zip)

(rename the .zip to .xpi)

If it still doesn't work, can you send me the full error log, via email to fabrixxm at gmail if you prefer.

**Comment by gdsotirov** [comment]
> I'm supposing you're using the "br" locale on your computer, so it should try to load you "br" translation files.

Yes, but it's actually "bg".

> They looks fine as dtd file, the only thing I find is they are utf16-encoded.

I suppose my text editor was misconfigured (or configured for something else) at the moment I created the files and I'm sorry for this. It's now fixed and I created pull request #23.

> If that's the problem, can you try this new version with the two files converted to utf8 and see if it works?

I tried and apparently this was the problem, because I now have the Year view.

Thank you very much for the help! I really appreciate your efforts for bringing this great extension to Thunderbird 60 and I'll be eager to test the final version :-)

**Comment by fabrixxm** [comment]
@gdsotirov @crayxt 
There is what I hope it's the last pre-release:
https://github.com/fabrixxm/Year-View/releases/tag/v0.6.0-3
If you want to try it

**Comment by gdsotirov** [comment]
@fabrixxm Already testing it and no problems so far.

**Comment by fabrixxm** [comment]
New version is live on https://addons.thunderbird.net
